/* eslint-disable import/prefer-default-export */

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const REVERSE_CURRENCY = 'REVERSE_CURERNCY';
export const CHANGE_AMOUNT = 'CHANGE_CURRENCY_AMOUNT';
export const CHANGE_PRIMARY_CURRENCY = 'CHANGE_PRIMARY_CURRENCY';
export const CHANGE_SECONDARY_CURRENCY = 'CHANGE_SECONDARY_CURRENCY';
